config/routes.rb
Rails.application.routes.draw do
  root "trivias#index"
  get "trivias/index"
  get "trivias/download", to: "trivias#download"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/trivias_controller.rb
class TriviasController < ApplicationController

  def index
    number = (params[:number] || 15).to_i.clamp(1, 15) # default 15 when no value is give, limited query to only between 1 and 15 to prevent cookie overflow
    
    # fetch trivia data with param
    @trivia_questions = OpentdbService.fetch_trivia(number)

    # storing only specific fields to session to prevent cookie overflow
    session[:trivia_questions] = @trivia_questions.map { |q| q.slice("question", "correct_answer") }

    # checking stored session questions in rails console
    Rails.logger.debug "Stored Trivia Questions: #{session[:trivia_questions].inspect}"
  end
  
  def download
    session_questions = session[:trivia_questions]

    # format response
    respond_to do |format|
      format.json { send_data DownloadService.to_json(session_questions), filename: "trivia-questions.json", type: "application/json"}
      format.csv { send_data DownloadService.to_csv(session_questions), filename: "trivia-questions.csv" }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trivias_helper.rb
module TriviasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Api Fetching App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trivias/index.html.erb
<div class="main_div">
<div class="title">
<h1>True or False Trivia Questions</h1>
</div>

<!-- fetching logic -->
<div class="trivia_form">
<form action="<%= trivias_index_path %>" method="get">
  <label for="number">Enter number of trivia questions:</label>
  <input type="number" id="number" name="number" min="1" max="15" required>
  <button type="submit">Fetch Trivia</button>
</form>
</div>

<!-- table displaying logic -->
<% if session[:trivia_questions].present? %>
<div class="trivia_table">
  <table border="1" cellpadding="10" cellspacing="0">
    <thead>
      <tr>
        <th>Question</th>
        <th>Answer</th>
      </tr>
    </thead>
    <tbody>
      <% session[:trivia_questions].each do |item| %>
        <tr>
          <td><%= item["question"].html_safe %></td>
          <td><%= item["correct_answer"].html_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<!-- buttons that lead to download json and csv -->
<div class="button_block">
<% if session[:trivia_questions].present? %>
  <button class="print_button" onclick="printToConsole()">Print to Console</button>
  <button class="download_json_button" onclick="downloadFile('json')">Download as JSON</button>
  <button class="download_csv_button" onclick="downloadFile('csv')">Download as CSV</button>
<% end %>
</div>

<!-- print to browser console logic -->
<script>
  function printToConsole() {
    let triviaData = <%= raw session[:trivia_questions].to_json %>; 
    console.log("Trivia Questions:", triviaData);
  }

  function downloadFile(format) {
    window.location.href = `<%= trivias_download_path %>.${format}`;
  }
</script>
<!-- logic leading to download_path for json and csv -->

<% else %>
  <p>No trivia questions available.</p>
<% end %>
</div>